mooculus/calculus

textbook/implicitDifferentiation/digInImplicitDifferentiation.tex, textbook/linearApproximation/dinInLinearApproximation, textbook/substitution/digInIdeaOfSubstitution, textbook/trigonometricDerivatives/digInDerivativesOfTrigFunctions, textbook/workingWithSubstitution/digInWorkingWithSubstitution
Wrote the dig in's for the following 5 sections
1)  Idea of substitution
2)  Working with substitution
3)  Implicit differentiation
4)  Derivatives of trigonometric functions
5)  Linear approximation
=> 5 dig in Sections

limitLaws/digInTheSqueezeTheorem.tex, quadricSurfaces/exercises/quadricSurface3.ditto1.tex, quadricSurfaces/exercises/quadricSurface4.ditto1.tex, understandingFunctions/exercises/piecewise2.tex
Bart made some additional changes. In the meantime, Tae Eun added some clarification on the Squeeze Theorem. No conflicts.
=> Merge Request

chainRule/exercises/basicChainRule2.tex, chainRule/exercises/basicChainRule5.tex, chainRule/exercises/basicChainRule6.tex, chainRule/exercises/harderChainRule1.tex, chainRule/exercises/harderChainRule5.tex, chainRule/exercises/harderChainRule6.tex, definitionOfTheDerivative/exercises/derivativeTangentLine2.tex, higherOrderDerivativesAndGraphs/exercises/higherOrderDerivatives1.tex, higherOrderDerivativesAndGraphs/exercises/orderDerivatives1.tex, higherOrderDerivativesAndGraphs/exercises/orderDerivatives2.tex, higherOrderDerivativesAndGraphs/exercises/orderDerivatives3.tex, higherOrderDerivativesAndGraphs/exercises/orderDerivatives4.tex, higherOrderDerivativesAndGraphs/exercises/velocityFromGraph1.tex, productAndQuotientRules/exercises/exerciseList.tex
We edited the assignments for Product/Quotient Rule, Chain Rule, and HOD. In particular, we fixed typos and cleaned up the formatting for the solutions.
=> Assignment Changes

antiderivatives/digInBasicAntiderivatives.tex
The typos are obvious. This only affects one activity. So even if students were to update, they wouldn't lose their work for the entire textbook. Just the one section (activity).
=> I fixed a few typos in the textbook section.

interpretingTheGradient/digInGradient.tex, interpretingTheGradient/titlePage.tex
Bart and I were messing around with Xake behavior. So we made some changes to Calc 3 files to force redeployments. I am confident they were never meant to be permanent. So I ran some git reverts to restore the original files.
=> Revert Silly Changes

multipleIntegrals/digInIntegralsOverTrivialRegions.tex
If my intuition isn't leading me astray, I think we should have F(x, y, z) and dV since we are considering triple integrals here.
=> Possible content correction

multipleIntegrals/digInIntegralsOverTrivialRegions.tex
Another possible simple content fix.
=> Added "z" into the region definition

computationsAndInterpretations/exercisesSurfaceArea/setup1.tex
0 < x should be written as 0 \le x where as it is written as 0 le x in computationsAndInterpretations/exercisesSurfaceArea/setup1.tex.
=> Update minor typo in homework

commonCoordinates/digInSphericalCoordinates.tex
I believe (?) this should be the order here, since that's what the picture shows, and what the theorem uses below.
=> Changed order to (rho, theta, phi)

greensTheorem/digInDivergenceAndGreensTheorem.tex
I believe (?) this part should be y'(t), seeing as n'(t) = <y'(t), -x'(t)>.
=> Changed x'(t) to y'(t)

greensTheorem/digInDivergenceAndGreensTheorem.tex
I think it should be divergence, as the expression gives divergence
=> Switched curl to divergence

parametricEquations/exercises/tangentLine4.tex
https://www.desmos.com/calculator/qmvnwfhyju
https://www.wolframalpha.com/input/?i=y+-+35%2F8+%3D+(27%2F20)+(x-33%2F4),+solve+for+y
=> Fix incorrect tangent line

continuityOfFunctionsOfSeveralVariables/exercises/limitTrueFalse1.tex
For the value of m for which y=mx passes through (3,1), the answer should be 1/3, not 3 - that passes through (1,3).
=> Corrected solution

partialDerivativesAndTheGradientVector/exercises/gradient3.tex
If you subtract you get: 4x-2y=0 - (2y-x+4=0) which gives 5x-4y-4=0. But if you add you get: 4x-2y=0 + (2y-x+4=0) which gives 3x+4=0 -> 3x=-4.
=> Corrected Wording

trigonometricIntegrals/digInTrigonometricIntegrals.tex
Changed "complimentary" to "complementary," since "complementary" is the correct word to use in this context.
=> Fix incorrect choice of word

moreThanOneRate/digInMoreThanOneRate.tex
=> removed redundant comma

higherOrderDerivativesAndGraphs/digInPositionVelocityAndAcceleration.tex
=> fix for #470

separableDifferentialEquations/digInSeparableDifferentialEquations.tex
The word "give" seemed to be unnecessary, so it should be removed.
=> Remove redundant word

maximumsAndMinimums/digInMaximumsAndMinimums.tex
fixed #474 (though it is not strictly an error, but I feel like this is more clear)
=> fixed # 474

accumulatedCrossSections/exercises/crossSections2Ways.tex
Found a typo while doing the homework.
=> fixed spelling error: fine -> find

review/refreshLimits/limitsOfRationalFunctionsReview.tex
Deleted 'indicate this.' from the problem. It appears it is either misplaced or at least a period is misplaced.
=> removed out of place sentence fragment

integralTest/digInIntegralTest.tex
This is in response to the issue #502
=> corrected plot 1/x^2

limitsOfSequences/exercises/sequenceComputeLimits2.tex
Closed the sin(...) function with a missing ).
=> Added missing parentheses
